//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 02:57:25 PM CEST 
//


package com.secunet.eidserver.testbed.common.types.testcase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for stepType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stepType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.secunet.com&gt;testStepType"&gt;
 *       &lt;attribute name="interface" use="required" type="{http://www.secunet.com}targetInterfaceType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stepType", propOrder = {
    "value"
})
public class StepType {

    @XmlValue
    protected TestStepType value;
    @XmlAttribute(name = "interface", required = true)
    protected TargetInterfaceType _interface;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link TestStepType }
     *     
     */
    public TestStepType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestStepType }
     *     
     */
    public void setValue(TestStepType value) {
        this.value = value;
    }

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link TargetInterfaceType }
     *     
     */
    public TargetInterfaceType getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetInterfaceType }
     *     
     */
    public void setInterface(TargetInterfaceType value) {
        this._interface = value;
    }

}
