//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Änderungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2017.03.02 um 01:01:12 PM CET 
//


package com.secunet.eidserver.testbed.common.types.testcase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java-Klasse für testStepType.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * <p>
 * <pre>
 * &lt;simpleType name="testStepType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IN_ATTACHED_WEBPAGE"/>
 *     &lt;enumeration value="IN_BAD_REQUEST"/>
 *     &lt;enumeration value="IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE"/>
 *     &lt;enumeration value="IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE_REQCHAT_SET1"/>
 *     &lt;enumeration value="IN_DID_AUTHENTICATE_EAC_2_INPUTTYPE"/>
 *     &lt;enumeration value="IN_DID_AUTHENTICATE_EACADDITIONALINPUTTYPE"/>
 *     &lt;enumeration value="IN_DIDLIST"/>
 *     &lt;enumeration value="IN_DISCONNECT"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_AGEPLACE"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_EIDCARD_2"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_EIDCARD_3"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_ERROR"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_ERROR_2"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_NORESULTYET"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_RESTRICTEDID"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_SET1"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_PLACE"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_AGE"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_PLACE_OPTIONAL"/>
 *     &lt;enumeration value="IN_GETRESULT_RESPONSE_AGE_OPTIONAL"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST_TWO_REQUESTCOUNTERS"/>
 *     &lt;enumeration value="IN_GETSERVERINFO_RESPONSE"/>
 *     &lt;enumeration value="IN_INITIALIZE_FRAMEWORK"/>
 *     &lt;enumeration value="IN_MISC"/>
 *     &lt;enumeration value="IN_SAML_ASSERTION"/>
 *     &lt;enumeration value="IN_START_PAOS_RESPONSE"/>
 *     &lt;enumeration value="IN_START_PAOS_RESPONSE_INTERNAL_ERROR"/>
 *     &lt;enumeration value="IN_START_PAOS_RESPONSE_CUSTOM_ERROR"/>
 *     &lt;enumeration value="IN_TC_TOKEN"/>
 *     &lt;enumeration value="IN_TC_TOKEN_ATTACHED"/>
 *     &lt;enumeration value="IN_TC_TOKEN_SAML_ATTACHED"/>
 *     &lt;enumeration value="IN_TLS"/>
 *     &lt;enumeration value="IN_TRANSMIT"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE_NO_PSK"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE_ERROR"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE_PSK"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE_PSK_ERROR"/>
 *     &lt;enumeration value="IN_USEID_RESPONSE_UNIQUE"/>
 *     &lt;enumeration value="OUT_CALL_SAML_INCL_AUTHNREQUEST"/>
 *     &lt;enumeration value="OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGALG_NO_SIGNATURE"/>
 *     &lt;enumeration value="OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGNATURE"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CHAT"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHAT"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_IDPICC"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CUSTOM_CHAT"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHALLENGE"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_INTERNALERROR"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_CUSTOM_AUTHTOKEN"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_EFCARDSECURITY"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_AUTHENTICATIONTOKEN"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_EFCARDSECURITY"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_AUTHENTICATIONTOKEN"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_NONCE"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_NONCE"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_INTERNALERROR"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B"/>
 *     &lt;enumeration value="OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B_MANDATORY"/>
 *     &lt;enumeration value="OUT_DIDLIST"/>
 *     &lt;enumeration value="OUT_DISCONNECT"/>
 *     &lt;enumeration value="OUT_GET_TCTOKEN"/>
 *     &lt;enumeration value="OUT_GET_ATTACHED_WEBPAGE"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST_NO_REQUESTCOUNTER"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST_NO_SID"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST_REQUESTCOUNTER"/>
 *     &lt;enumeration value="OUT_GETRESULT_REQUEST_SID"/>
 *     &lt;enumeration value="OUT_GETSERVERINFO_REQUEST"/>
 *     &lt;enumeration value="OUT_INITIALIZE_FRAMEWORK_RESPONSE"/>
 *     &lt;enumeration value="OUT_INITIALIZE_FRAMEWORK_RESPONSE_EMPTY_RESULT"/>
 *     &lt;enumeration value="OUT_MISC"/>
 *     &lt;enumeration value="OUT_SAML_ASSERTION"/>
 *     &lt;enumeration value="OUT_START_PAOS"/>
 *     &lt;enumeration value="OUT_START_PAOS_DIDPROTOCOLS"/>
 *     &lt;enumeration value="OUT_TLS_ATTACHED"/>
 *     &lt;enumeration value="OUT_TLS_ECARDAPI"/>
 *     &lt;enumeration value="OUT_TLS_EID"/>
 *     &lt;enumeration value="OUT_TLS_SAML"/>
 *     &lt;enumeration value="OUT_TRANSMIT"/>
 *     &lt;enumeration value="OUT_TRANSMIT_INVALID_MAC"/>
 *     &lt;enumeration value="OUT_TRANSMIT_NO_APDUS"/>
 *     &lt;enumeration value="OUT_TRANSMIT_NO_MAC"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_ALL"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_NO_AGEVERIFICATIONREQUEST"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_NO_PLACEVERIFICATIONREQUEST"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_NO_USEOPERATIONS"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_PSK"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_SET1"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_PLACE"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_AGE"/>
 *     &lt;enumeration value="OUT_USEID_REQUEST_NO_XMLSIGNATURE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "testStepType")
@XmlEnum
public enum TestStepType {

    IN_ATTACHED_WEBPAGE("IN_ATTACHED_WEBPAGE"),
    IN_BAD_REQUEST("IN_BAD_REQUEST"),
    IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE("IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE"),
    @XmlEnumValue("IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE_REQCHAT_SET1")
    IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE_REQCHAT_SET_1("IN_DID_AUTHENTICATE_EAC_1_INPUTTYPE_REQCHAT_SET1"),
    IN_DID_AUTHENTICATE_EAC_2_INPUTTYPE("IN_DID_AUTHENTICATE_EAC_2_INPUTTYPE"),
    IN_DID_AUTHENTICATE_EACADDITIONALINPUTTYPE("IN_DID_AUTHENTICATE_EACADDITIONALINPUTTYPE"),
    IN_DIDLIST("IN_DIDLIST"),
    IN_DISCONNECT("IN_DISCONNECT"),
    IN_GETRESULT_RESPONSE("IN_GETRESULT_RESPONSE"),
    IN_GETRESULT_RESPONSE_AGEPLACE("IN_GETRESULT_RESPONSE_AGEPLACE"),
    IN_GETRESULT_RESPONSE_EIDCARD_2("IN_GETRESULT_RESPONSE_EIDCARD_2"),
    IN_GETRESULT_RESPONSE_EIDCARD_3("IN_GETRESULT_RESPONSE_EIDCARD_3"),
    IN_GETRESULT_RESPONSE_ERROR("IN_GETRESULT_RESPONSE_ERROR"),
    IN_GETRESULT_RESPONSE_ERROR_2("IN_GETRESULT_RESPONSE_ERROR_2"),
    IN_GETRESULT_RESPONSE_NORESULTYET("IN_GETRESULT_RESPONSE_NORESULTYET"),
    IN_GETRESULT_RESPONSE_RESTRICTEDID("IN_GETRESULT_RESPONSE_RESTRICTEDID"),
    @XmlEnumValue("IN_GETRESULT_RESPONSE_SET1")
    IN_GETRESULT_RESPONSE_SET_1("IN_GETRESULT_RESPONSE_SET1"),
    IN_GETRESULT_RESPONSE_PLACE("IN_GETRESULT_RESPONSE_PLACE"),
    IN_GETRESULT_RESPONSE_AGE("IN_GETRESULT_RESPONSE_AGE"),
    IN_GETRESULT_RESPONSE_PLACE_OPTIONAL("IN_GETRESULT_RESPONSE_PLACE_OPTIONAL"),
    IN_GETRESULT_RESPONSE_AGE_OPTIONAL("IN_GETRESULT_RESPONSE_AGE_OPTIONAL"),
    OUT_GETRESULT_REQUEST_TWO_REQUESTCOUNTERS("OUT_GETRESULT_REQUEST_TWO_REQUESTCOUNTERS"),
    IN_GETSERVERINFO_RESPONSE("IN_GETSERVERINFO_RESPONSE"),
    IN_INITIALIZE_FRAMEWORK("IN_INITIALIZE_FRAMEWORK"),
    IN_MISC("IN_MISC"),
    IN_SAML_ASSERTION("IN_SAML_ASSERTION"),
    IN_START_PAOS_RESPONSE("IN_START_PAOS_RESPONSE"),
    IN_START_PAOS_RESPONSE_INTERNAL_ERROR("IN_START_PAOS_RESPONSE_INTERNAL_ERROR"),
    IN_START_PAOS_RESPONSE_CUSTOM_ERROR("IN_START_PAOS_RESPONSE_CUSTOM_ERROR"),
    IN_TC_TOKEN("IN_TC_TOKEN"),
    IN_TC_TOKEN_ATTACHED("IN_TC_TOKEN_ATTACHED"),
    IN_TC_TOKEN_SAML_ATTACHED("IN_TC_TOKEN_SAML_ATTACHED"),
    IN_TLS("IN_TLS"),
    IN_TRANSMIT("IN_TRANSMIT"),
    IN_USEID_RESPONSE("IN_USEID_RESPONSE"),
    IN_USEID_RESPONSE_NO_PSK("IN_USEID_RESPONSE_NO_PSK"),
    IN_USEID_RESPONSE_ERROR("IN_USEID_RESPONSE_ERROR"),
    IN_USEID_RESPONSE_PSK("IN_USEID_RESPONSE_PSK"),
    IN_USEID_RESPONSE_PSK_ERROR("IN_USEID_RESPONSE_PSK_ERROR"),
    IN_USEID_RESPONSE_UNIQUE("IN_USEID_RESPONSE_UNIQUE"),
    OUT_CALL_SAML_INCL_AUTHNREQUEST("OUT_CALL_SAML_INCL_AUTHNREQUEST"),
    OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGALG_NO_SIGNATURE("OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGALG_NO_SIGNATURE"),
    OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGNATURE("OUT_CALL_SAML_INCL_AUTHNREQUEST_NO_SIGNATURE"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CHAT("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CHAT"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHAT("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHAT"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_IDPICC("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_IDPICC"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CUSTOM_CHAT("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITH_CUSTOM_CHAT"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHALLENGE("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_WITHOUT_CHALLENGE"),
    OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_INTERNALERROR("OUT_DID_AUTHENTICATE_EAC_1_OUTPUTTYPE_INTERNALERROR"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_CUSTOM_AUTHTOKEN("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_CUSTOM_AUTHTOKEN"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_EFCARDSECURITY("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_EFCARDSECURITY"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_AUTHENTICATIONTOKEN("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_AUTHENTICATIONTOKEN"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_EFCARDSECURITY("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_EFCARDSECURITY"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_AUTHENTICATIONTOKEN("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_AUTHENTICATIONTOKEN"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_NONCE("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_NO_NONCE"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_NONCE("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_DUPLICATED_NONCE"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_INTERNALERROR("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_A_INTERNALERROR"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B"),
    OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B_MANDATORY("OUT_DID_AUTHENTICATE_EAC_2_OUTPUTTYPE_B_MANDATORY"),
    OUT_DIDLIST("OUT_DIDLIST"),
    OUT_DISCONNECT("OUT_DISCONNECT"),
    OUT_GET_TCTOKEN("OUT_GET_TCTOKEN"),
    OUT_GET_ATTACHED_WEBPAGE("OUT_GET_ATTACHED_WEBPAGE"),
    OUT_GETRESULT_REQUEST("OUT_GETRESULT_REQUEST"),
    OUT_GETRESULT_REQUEST_NO_REQUESTCOUNTER("OUT_GETRESULT_REQUEST_NO_REQUESTCOUNTER"),
    OUT_GETRESULT_REQUEST_NO_SID("OUT_GETRESULT_REQUEST_NO_SID"),
    OUT_GETRESULT_REQUEST_REQUESTCOUNTER("OUT_GETRESULT_REQUEST_REQUESTCOUNTER"),
    OUT_GETRESULT_REQUEST_SID("OUT_GETRESULT_REQUEST_SID"),
    OUT_GETSERVERINFO_REQUEST("OUT_GETSERVERINFO_REQUEST"),
    OUT_INITIALIZE_FRAMEWORK_RESPONSE("OUT_INITIALIZE_FRAMEWORK_RESPONSE"),
    OUT_INITIALIZE_FRAMEWORK_RESPONSE_EMPTY_RESULT("OUT_INITIALIZE_FRAMEWORK_RESPONSE_EMPTY_RESULT"),
    OUT_MISC("OUT_MISC"),
    OUT_SAML_ASSERTION("OUT_SAML_ASSERTION"),
    OUT_START_PAOS("OUT_START_PAOS"),
    OUT_START_PAOS_DIDPROTOCOLS("OUT_START_PAOS_DIDPROTOCOLS"),
    OUT_TLS_ATTACHED("OUT_TLS_ATTACHED"),
    OUT_TLS_ECARDAPI("OUT_TLS_ECARDAPI"),
    OUT_TLS_EID("OUT_TLS_EID"),
    OUT_TLS_SAML("OUT_TLS_SAML"),
    OUT_TRANSMIT("OUT_TRANSMIT"),
    OUT_TRANSMIT_INVALID_MAC("OUT_TRANSMIT_INVALID_MAC"),
    OUT_TRANSMIT_NO_APDUS("OUT_TRANSMIT_NO_APDUS"),
    OUT_TRANSMIT_NO_MAC("OUT_TRANSMIT_NO_MAC"),
    OUT_USEID_REQUEST("OUT_USEID_REQUEST"),
    OUT_USEID_REQUEST_ALL("OUT_USEID_REQUEST_ALL"),
    OUT_USEID_REQUEST_NO_AGEVERIFICATIONREQUEST("OUT_USEID_REQUEST_NO_AGEVERIFICATIONREQUEST"),
    OUT_USEID_REQUEST_NO_PLACEVERIFICATIONREQUEST("OUT_USEID_REQUEST_NO_PLACEVERIFICATIONREQUEST"),
    OUT_USEID_REQUEST_NO_USEOPERATIONS("OUT_USEID_REQUEST_NO_USEOPERATIONS"),
    OUT_USEID_REQUEST_PSK("OUT_USEID_REQUEST_PSK"),
    @XmlEnumValue("OUT_USEID_REQUEST_SET1")
    OUT_USEID_REQUEST_SET_1("OUT_USEID_REQUEST_SET1"),
    OUT_USEID_REQUEST_PLACE("OUT_USEID_REQUEST_PLACE"),
    OUT_USEID_REQUEST_AGE("OUT_USEID_REQUEST_AGE"),
    OUT_USEID_REQUEST_NO_XMLSIGNATURE("OUT_USEID_REQUEST_NO_XMLSIGNATURE");
    private final String value;

    TestStepType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TestStepType fromValue(String v) {
        for (TestStepType c: TestStepType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
