package com.secunet.eidserver.testbed.common.enumerations;


public enum Replaceable
{
	AUTHENTICATEDAUXILIARYDATA, CA_PRIVATE, CANDIDATE_HOSTNAME, CANDIDATE_PATH, CANDIDATE_URL, CERTIFICATE_DESCRIPTION, COMMUNICATIONERRORADDRESS, CV_DV_CERTIFICATE, CHALLENGE, IDPICC, NONCE, EFCARDACCESS, EFCARDSECURITY, EPHEMERALPUBLICKEY, ISSUE_INSTANT, PSK, REFRESHADDRESS, SAML_ID, SAML_PROCESSOR_HOSTNAME, SAML_PROCESSOR_PATH, SAML_PROCESSOR_URL, SESSIONIDENTIFIER, USER_AGENT, TESTBED_HOSTNAME, TESTBED_REFRESH_ADDRESS, TESTBED_USER_AGENT_NAME, TESTBED_USER_AGENT_MAJOR, TESTBED_USER_AGENT_MINOR, TESTBED_USER_AGENT_SUBMINOR, ATTACHED_TCTOKEN, ATTACHED_TCTOKEN_HOSTNAME, ATTACHED_TCTOKEN_PATH, ATTACHED_WEBPAGE, ATTACHED_WEBPAGE_HOSTNAME, ATTACHED_WEBPAGE_PATH, EID_INTERFACE_HOSTNAME, EID_INTERFACE_PATH, EID_INTERFACE_URL, REQUESTCOUNTER, PLACE_COMPARISON_VALUE, AGE_COMPARISON_VALUE, DOCUMENT_VALIDITY;

	public static final String BEGIN_TEXTMARK = "[";
	public static final String END_TEXTMARK = "]";

	public String getTextMark()
	{
		return BEGIN_TEXTMARK + this.name() + END_TEXTMARK;
	}
}
